version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - './frontend/src:/app/src'
    stdin_open: true
    tty: true
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - './backend/src:/app/src'
  mongo:
    image: mongo:5-focal
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: